### ISSUE TITLE
Subscription names don't interpolate variables

### ISSUE THREAD

**Issue by dnsbty** [gen1321/simple_graphql_client#2]
Thank you for this library! I was going to build out the same thing when I stumbled across this and found out it does pretty much everything I need. I just wanted to point out a little bug I found.

I have an application which needs to subscribe to multiple versions of the same query. For example something like this query:

```graphql
subscription userUpdated($userUid: ID!) {
      userUpdated(userUid: $userUid) {
        name
        points
      }
    }
```

So if I want to subscribe to updates on 4 different users, I subscribe to each one individually. Then any time one of them is updated, the handler function for each one gets hit since the name it checks against is `userUpdated($userUid: ID!)`. This should probably come up with a way to swap out the `ID!` part for the actual variable value that I pass in so that it would have a unique value every time.

**Comment by gen1321** [comment]
@dnsbty Hey! I will fix it asap :) thanks for reporting

**Comment by gen1321** [comment]
@dnsbty oh u already fixed it in your fork, sorry for the late response! I will merge ur changes to master
